#!/usr/bin/perl

if(scalar(@ARGV) != 1) {
    print "Usage: ~ <size displayed by 'ls -s'>\n\n";
    exit(1);
}

$fileList = `ls -s -1`;
@files = split(/\n/, $fileList);

$limit = $ARGV[0];

print "limit = $limit\n";

if($limit eq "") {
    print "use:\n";
    print "rmSmall.pl <size>\n";
    return;
}

my($size, $fname);
foreach $file (@files) {
    $file =~ s/^\s*//g;
    $file =~ s/\s$//g;
    ($size, $fname) = split(/\s+/, $file);

    if($size <= $limit) {
	print "removing $fname of size $size\n";
	`rm -rf $fname`;
    }
    else {
#	print "keeping $fname of size $size\n";
    }	
}
